name: Deploy to Apache Server with Rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Rsync files to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          RSYNC_EXIT_STATUS=0
          rsync -avz --delete --exclude=.git --exclude=.github -e "ssh -o StrictHostKeyChecking=no" ./ ${SERVER_USER}@${SERVER_IP}:/var/www/jup.eco/ || RSYNC_EXIT_STATUS=$?
          if [ $RSYNC_EXIT_STATUS -eq 0 ]; then
            echo "Rsync completed successfully. Restarting Apache..."
            sudo systemctl restart apache2
          else
            echo "Rsync failed with exit status $RSYNC_EXIT_STATUS"
            exit $RSYNC_EXIT_STATUS
          fi
